### ISSUE TITLE
Missing migrations table

### ISSUE THREAD

**Issue by ArraysNL** [cuisine-wp/chef-sections#2]
After installing both Cuisine and Chef Sections. The following error shows up.

`WordPress database error Table 'local.wp_migrations' doesn't exist for query SELECT * FROM `wp_migrations`  WHERE `name` = 'cuisinedatabasemigrationssetup'  LIMIT 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, Cuisine::getInstance, Cuisine->__construct, Cuisine->load, require_once('/plugins/cuisine/Classes/Database/Migrations/Setup.php'), Cuisine\Wrappers\StaticInstance::getInstance, Cuisine\Database\Migrations\Migration->__construct, Cuisine\Database\Migrations\Migration->getTimestamp, Cuisine\Database\Record->first, Cuisine\Database\Record->results, Cuisine\Database\Query->results`

Looks like a migration table must be created after installation, which won't happen.

**Comment by lucprincen** [comment]
Thanks for bringing this to my attention. Will fix this asap.
For now, this can be fixed using a wp cli command on your install:
`wp cuisine migrate`

**Comment by ArraysNL** [comment]
Thanks, Fixes the missing tables problem for now

**Comment by lucprincen** [comment]
Should be fixed in the latest master of cuisine:
https://github.com/cuisine-wp/chef-sections/commit/c7471dd8f10628a6f378de86ec24cbb0aa897158
